# Generated by Django 4.2 on 2026-05-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.CharField(blank=True, choices=[('ODD', 'Odd'), ('EVEN', 'Even')], max_length=10, null=True),
        ),
    ]
